### ISSUE TITLE
Don't work ageLossDBNO in server 1.20.1

### ISSUE THREAD

**Issue by vasilyvaganov** [TheDrOfDoctoring/Vampiric-Ageing#11]
I set the ageLossDBNO=0 parameter on the server so that the "age" level does not fall during resurrection, but in the end it still falls by one level

**Comment by vasilyvaganov** [comment]
And please add a blood loss function for each damage you receive when you have little health left and the shouldOnlyDieFromKillingSources = true function is enabled.
And when you lose blood, you can die

**Comment by TheDrOfDoctoring** [comment]
should be fixed in [latest release](https://legacy.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/5207235l). I've also included the suggested blood loss mechanic as an optional config.

**Comment by vasilyvaganov** [comment]
I'm back with my ideas. Everything turned out fine, but I'm worried about blood loss with a small amount of health. Is it possible to make blood be lost depending on the damage received, while the damage false counts armor? I.e., not a static loss of 3 units of blood. Sorry for my English 😅

**Comment by vasilyvaganov** [comment]
I came back with my ideas. Everything turned out great, but I'm worried about blood loss with a small amount of health. Is it possible to make the blood loss depend on the damage received, but also take into account the armor? that is, it is not a static loss of 3 units of blood. Sorry for my English 😅

**Comment by TheDrOfDoctoring** [comment]
yeah, I wasn't sure on how I wanted to have the blood loss handled. I think it would probably be best with something like this:
- No bloodloss below a minimum damage threshold
- Blood loss then scales with damage from that point
- Bloodloss continues scaling up to a point where it caps.

All these values could then be configurable, with the blood loss scale being the damage multiplied by some number, e.g a quarter of the damage dealt is done as blood loss. If that seems reasonable to you I'll change it to working like that.

**Comment by vasilyvaganov** [comment]
Yes, it would be nice to see that! 😅

**Comment by TheDrOfDoctoring** [comment]
included for [latest release](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/5212314)

**Comment by TheDrOfDoctoring** [comment]
For now, I'll leave the values as they are since I don't really want to release another build for some minor config changes. I'll include the changed values in the next update, whenever that is.
