### ISSUE TITLE
Hunters can interact and attack in Limited Bat mode

### ISSUE THREAD

**Issue by Food-dude-99** [TheDrOfDoctoring/Vampiric-Ageing#12]
Hello Dr, I am using the latest version of vampirism and vampiric ageing in Minecraft version 1.20.1.

I discovered that Hunters in Limited bat mode can interact with blocks and attack mobs. I didn't know if this was intentional or not so I decided to make this report. I do have it where vampires cannot interact with anything in bat mode if the ability is supposed to be affected by that. 

Thanks,
Food_dude_99

**Comment by TheDrOfDoctoring** [comment]
ty, should be fixed in the [latest release](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/5350582)
