### ISSUE TITLE
[Bug] Werewolves cannot gain devour points

### ISSUE THREAD

**Issue by schindlershadow** [TheDrOfDoctoring/Vampiric-Ageing#16]
finishing off a mob with bite is not giving a werewolf lord devour points
![2024-10-19_00 02 09](https://github.com/user-attachments/assets/7853afe4-31b3-4e89-870a-6a29db8f8dc2)
this screenshot was after killing many mobs, it hasn't moved from 30

**Comment by TheDrOfDoctoring** [comment]
thanks for the report, should be fixed in the [latest release](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/5824069)

**Comment by schindlershadow** [comment]
this is still not fixed as of 1.4.2

**Comment by TheDrOfDoctoring** [comment]
Are you killing any of the specifically devour tagged entities? (faction mobs like hunters / vampires for more points, animals and other vanilla mobs worthless)

**Comment by schindlershadow** [comment]
I managed to finally get a few points using hunters. what is the tag for devour entities? would be cool to see how many points listed in a wiki or something and maybe a guide for adding additional entities

**Comment by TheDrOfDoctoring** [comment]
The tags can be seen here <https://github.com/TheDrOfDoctoring/Vampiric-Ageing/tree/1.20.1/src/generated/resources/data/vampiricageing/tags/entity_types>. You can add entities like any other tag by using a datapack, with the points for each configurable in the werewolf ageing config.
