### ISSUE TITLE
tainted hunter can teleport while using limited bat mode, while vampire can't teleport while using bat mode 

### ISSUE THREAD

**Issue by tf2piro** [TheDrOfDoctoring/Vampiric-Ageing#17]
I don't know if this should considered as a bug or intentional, but at least I think it's weird to see that a tainted hunter can teleport while using bat mode but vampire can't do the same.

**Comment by TheDrOfDoctoring** [comment]
Fixed in dev, not pushing a release on CF immediately but will close the issue for now.

**Comment by tf2piro** [comment]
thanks =D
