### ISSUE TITLE
Crash while attacking vampires

### ISSUE THREAD

**Issue by CuchilloMucho** [TheDrOfDoctoring/Vampiric-Ageing#2]
got this crash, thought it was just vampyrisim, disabled this mod and the crash went away. Error: java.lang.ClassCastException: class de.teamlapen.vampirism.entity.vampire.BasicVampireEntity cannot be cast to class net.minecraft.world.entity.player.Player (de.teamlapen.vampirism.entity.vampire.BasicVampireEntity is in module vampirism@1.9.3 of loader 'TRANSFORMER' @c6c58ce; net.minecraft.world.entity.player.Player is in module minecraft@1.20.1 of loader 'TRANSFORMER' @c6c58ce)

**Comment by TheDrOfDoctoring** [comment]
Can you send the full crash report please? It'll be in `packfolder/crash-reports`

**Comment by TheDrOfDoctoring** [comment]
Should be fixed in the [latest release](https://legacy.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/4810344)
