### ISSUE TITLE
Crashing when Trying to launch server with mod

### ISSUE THREAD

**Issue by Hael-Lith** [TheDrOfDoctoring/Vampiric-Ageing#4]
https://pastebin.com/ZkvRRSXT

**Comment by TheDrOfDoctoring** [comment]
ty, should be fixed in the[ latest release.](https://legacy.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/4834776)

**Comment by Hael-Lith** [comment]
ok thank you also this is for version 1.16.5 i shouldve said that to start with
