### ISSUE TITLE
Vampiricaging-1.3.4 Incompatibility with Create 

### ISSUE THREAD

**Issue by NikoTheGreat** [TheDrOfDoctoring/Vampiric-Ageing#5]
Version 1.3.4 of Vampiric Aging crashes the game when run with the Create mod. Version 1.3.3 works just fine if I regress versions. Something in the new version is causing the incompatibility.

**Comment by NikoTheGreat** [comment]
I'm using Curse Forge to test mods. See picture below for test scenario:
![image](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/16003271/68c630df-e6f6-4d2a-a3fa-f9c701338b0e)

**Comment by NikoTheGreat** [comment]
Here is the error message:
![image](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/16003271/95f64c90-7174-4ad6-8500-e69e76cec692)

**Comment by NikoTheGreat** [comment]
Here is the Crash FML:
[crash-2023-11-13_10.52.41-fml.txt](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/files/13336613/crash-2023-11-13_10.52.41-fml.txt)

**Comment by NikoTheGreat** [comment]
Here is the Log:
[latest.log](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/files/13336627/latest.log)

**Comment by NikoTheGreat** [comment]
I will notify of other incompatibilities if another test scenario fails.
God bless, and thank you for all your hard work! Your mod is great!

**Comment by TheDrOfDoctoring** [comment]
oops, not actually an incompatability with create, just an accidental hard dependency on werewolves that makes it look like its a conflict with create.
