### ISSUE TITLE
tainted hunter still get nausea even tainted level higher than no negative effects from bad food 

### ISSUE THREAD

**Issue by mtf8769** [TheDrOfDoctoring/Vampiric-Ageing#6]
![1](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/57584862/ad3acc44-9c04-4b3f-a390-3902b1f77b34)
![2](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/57584862/d121049c-2aac-4207-8696-8627559ed39c)
![2023-12-26](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/57584862/7a599b19-3444-4a4b-b57a-c6cda414d0e9)
no matter how much number changed,even 0,I still get nausea when eating human heart.
vampiric ageing version:1.16.5-1.3.11

**Comment by TheDrOfDoctoring** [comment]
ty, looks like it was only broken outside of dev due to remap, should be fixed in the [latest release](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/4986858)
