### ISSUE TITLE
Hunter ageing balance configuration issues

### ISSUE THREAD

**Issue by Goiabaaa** [TheDrOfDoctoring/Vampiric-Ageing#7]
As of right now, If you disable Tainted Blood mechanic, hunters will not get any damage boost with ageing and there is no configuration to give them damage outside of the Tainted Blood state. Make it so that you can configure Hunter damage scaling with age just as werewolves and vampires can, so that If you disable Tainted for balance reasons hunters still can benefit from ageing mechanic.

Also, add an option to disable Seniority Oil. It seems Seniority Oil damage configuration values are bugged because I reduced the base multiplier from 2.5 to 1.1 in the configs and it still does the same damage in game (71 damage with Sharpness 5 Ultimate Hunter Axe and Strenght 3 effect + Max Tainted Blood). And even without the strenght effect active, the damage value multiplier does not change. I hope this gets fixed so that hunters can be more balanced because this amount of damage is way too much broken.

**Comment by Goiabaaa** [comment]
https://github.com/TheDrOfDoctoring/Vampiric-Ageing/assets/126027644/f8e07382-0ade-44a1-8d48-02ca277d13cc

A video showing how absurd seniority oil values are with the current base settings and no possibility of change.

**Comment by TheDrOfDoctoring** [comment]
Thanks, it looks like seniority oil was bugged and was unintentionally doubling all damage (and a bit extra). I also forgot to ever give it a recipe, making it completely unobtainable in game.

As for the damage bonus, non-tainted hunters get access to a ``ageEnemyFactionDamageIncrease``. This makes the hunter do more damage against enemy faction members which I believe is more reasonable than giving hunters a flat damage bonus, as in a situation where vampirism is not the main mod in a server it helps prevent hunters from just being humans but better, as that bonus will only come into play against other players using the vampirism mod (or vampirism's entities).

I've also included some other changes the default configs to lessen the impact of ageing in some cases - more specifically nerfing the damage bonuses and max health provided, but also reducing the harshness of the vulnerability multiplier vampires.
