### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by ChapperNi** [TheDrOfDoctoring/Vampiric-Ageing#9]
[crash-2024-02-04_02.56.17-server.txt](https://github.com/TheDrOfDoctoring/Vampiric-Ageing/files/14156440/crash-2024-02-04_02.56.17-server.txt)

**Comment by TheDrOfDoctoring** [comment]
ty, should be fixed in the [latest release](https://legacy.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon/files/5080355)

**Comment by ChapperNi** [comment]
Thank you, super fast fix!
